services:
  frontend:
    image: nginx:latest
    restart: always
    ports:
      - 3333:80
    volumes:
      - /var/lib/jenkins/workspace/Yoontest/frontend:/usr/share/nginx/html
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    volumes:
    - /var/lib/jenkins/workspace/Yoontest/sql:/docker-entrypoint-initdb.d/
    command: ["--init-file", "/docker-entrypoint-initdb.d/*"]
  backend:
    volumes:
      - /var/lib/jenkins/workspace/Yoontest/backend:/backend
    build:
      context: .
      dockerfile: pydockerfile
    restart: always
