apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env: 
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "loginapp"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "123456"
          # env:
          #   - name: MYSQL_ROOT_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysql-credential
          #         key: password
          #   - name: MYSQL_DATABASE
          #     value: petclinic
          volumeMounts:
            - name: nfs-pv
              mountPath: /var/lib/mysql
              readOnly: false
      volumes:
        - name: nfs-pv
          persistentVolumeClaim:
            claimName: nfs-pvc
