apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  selector:
    matchLabels:
      volume: nfs-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      # storage size to use
      storage: 5Gi
  storageClassName: "" 
