apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
      containers:
        - name: database
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credential
                  key: password
                  # 시크릿 키 적용 명령어
                  # echo -n "root" > ./username
                  # echo -n "비밀번호" > ./password 
                  # k create secret generic mysql-credential --from-fle=./username --from-file=./password
            - name: MYSQL_DATABASE  # 데이터베이스 이름 환경변수
              value: petclinic  # 설정
          volumeMounts:
            - name: nfs-pv-test
              mountPath: /var/lib/mysql
              readOnly: false

        - name: frontend
          image: nginx:latest
        
        - name: backend # pydockerfile 내용 반영
          image: python:latest
        
      volumes:
        - name: nfs-pv-test
          persistentVolumeClaim:
            claimName: nfs-pvc-test

          
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: web-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#       protocol: TCP
#       targetPort: 80
#   selector:
#     app: nginx
